// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package runtime_core.proxies;

public class CoreConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coreConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Runtime_Core.CoreConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AdminUserName("AdminUserName"),
		AdminUserRole("AdminUserRole"),
		ApplicationRootURL("ApplicationRootURL"),
		ClientQueryTimeout("ClientQueryTimeout"),
		FileSeparator("FileSeparator"),
		isGuestLoginEnabled("isGuestLoginEnabled"),
		GuestUserRoleName("GuestUserRoleName"),
		ModelerFileName("ModelerFileName"),
		ResourcesPath("ResourcesPath"),
		TempPath("TempPath"),
		SessionTimeout("SessionTimeout"),
		CoreConfiguration_Core("Runtime_Core.CoreConfiguration_Core");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CoreConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Runtime_Core.CoreConfiguration"));
	}

	protected CoreConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coreConfigurationMendixObject)
	{
		if (coreConfigurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Runtime_Core.CoreConfiguration", coreConfigurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Runtime_Core.CoreConfiguration");

		this.coreConfigurationMendixObject = coreConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CoreConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static runtime_core.proxies.CoreConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return runtime_core.proxies.CoreConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static runtime_core.proxies.CoreConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new runtime_core.proxies.CoreConfiguration(context, mendixObject);
	}

	public static runtime_core.proxies.CoreConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return runtime_core.proxies.CoreConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AdminUserName
	 */
	public final java.lang.String getAdminUserName()
	{
		return getAdminUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminUserName
	 */
	public final java.lang.String getAdminUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdminUserName.toString());
	}

	/**
	 * Set value of AdminUserName
	 * @param adminusername
	 */
	public final void setAdminUserName(java.lang.String adminusername)
	{
		setAdminUserName(getContext(), adminusername);
	}

	/**
	 * Set value of AdminUserName
	 * @param context
	 * @param adminusername
	 */
	public final void setAdminUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adminusername)
	{
		getMendixObject().setValue(context, MemberNames.AdminUserName.toString(), adminusername);
	}

	/**
	 * @return value of AdminUserRole
	 */
	public final java.lang.String getAdminUserRole()
	{
		return getAdminUserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminUserRole
	 */
	public final java.lang.String getAdminUserRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdminUserRole.toString());
	}

	/**
	 * Set value of AdminUserRole
	 * @param adminuserrole
	 */
	public final void setAdminUserRole(java.lang.String adminuserrole)
	{
		setAdminUserRole(getContext(), adminuserrole);
	}

	/**
	 * Set value of AdminUserRole
	 * @param context
	 * @param adminuserrole
	 */
	public final void setAdminUserRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adminuserrole)
	{
		getMendixObject().setValue(context, MemberNames.AdminUserRole.toString(), adminuserrole);
	}

	/**
	 * @return value of ApplicationRootURL
	 */
	public final java.lang.String getApplicationRootURL()
	{
		return getApplicationRootURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationRootURL
	 */
	public final java.lang.String getApplicationRootURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationRootURL.toString());
	}

	/**
	 * Set value of ApplicationRootURL
	 * @param applicationrooturl
	 */
	public final void setApplicationRootURL(java.lang.String applicationrooturl)
	{
		setApplicationRootURL(getContext(), applicationrooturl);
	}

	/**
	 * Set value of ApplicationRootURL
	 * @param context
	 * @param applicationrooturl
	 */
	public final void setApplicationRootURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationrooturl)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationRootURL.toString(), applicationrooturl);
	}

	/**
	 * @return value of ClientQueryTimeout
	 */
	public final java.lang.Long getClientQueryTimeout()
	{
		return getClientQueryTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientQueryTimeout
	 */
	public final java.lang.Long getClientQueryTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ClientQueryTimeout.toString());
	}

	/**
	 * Set value of ClientQueryTimeout
	 * @param clientquerytimeout
	 */
	public final void setClientQueryTimeout(java.lang.Long clientquerytimeout)
	{
		setClientQueryTimeout(getContext(), clientquerytimeout);
	}

	/**
	 * Set value of ClientQueryTimeout
	 * @param context
	 * @param clientquerytimeout
	 */
	public final void setClientQueryTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long clientquerytimeout)
	{
		getMendixObject().setValue(context, MemberNames.ClientQueryTimeout.toString(), clientquerytimeout);
	}

	/**
	 * @return value of FileSeparator
	 */
	public final java.lang.String getFileSeparator()
	{
		return getFileSeparator(getContext());
	}

	/**
	 * @param context
	 * @return value of FileSeparator
	 */
	public final java.lang.String getFileSeparator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileSeparator.toString());
	}

	/**
	 * Set value of FileSeparator
	 * @param fileseparator
	 */
	public final void setFileSeparator(java.lang.String fileseparator)
	{
		setFileSeparator(getContext(), fileseparator);
	}

	/**
	 * Set value of FileSeparator
	 * @param context
	 * @param fileseparator
	 */
	public final void setFileSeparator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fileseparator)
	{
		getMendixObject().setValue(context, MemberNames.FileSeparator.toString(), fileseparator);
	}

	/**
	 * @return value of isGuestLoginEnabled
	 */
	public final java.lang.Boolean getisGuestLoginEnabled()
	{
		return getisGuestLoginEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of isGuestLoginEnabled
	 */
	public final java.lang.Boolean getisGuestLoginEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isGuestLoginEnabled.toString());
	}

	/**
	 * Set value of isGuestLoginEnabled
	 * @param isguestloginenabled
	 */
	public final void setisGuestLoginEnabled(java.lang.Boolean isguestloginenabled)
	{
		setisGuestLoginEnabled(getContext(), isguestloginenabled);
	}

	/**
	 * Set value of isGuestLoginEnabled
	 * @param context
	 * @param isguestloginenabled
	 */
	public final void setisGuestLoginEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isguestloginenabled)
	{
		getMendixObject().setValue(context, MemberNames.isGuestLoginEnabled.toString(), isguestloginenabled);
	}

	/**
	 * @return value of GuestUserRoleName
	 */
	public final java.lang.String getGuestUserRoleName()
	{
		return getGuestUserRoleName(getContext());
	}

	/**
	 * @param context
	 * @return value of GuestUserRoleName
	 */
	public final java.lang.String getGuestUserRoleName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GuestUserRoleName.toString());
	}

	/**
	 * Set value of GuestUserRoleName
	 * @param guestuserrolename
	 */
	public final void setGuestUserRoleName(java.lang.String guestuserrolename)
	{
		setGuestUserRoleName(getContext(), guestuserrolename);
	}

	/**
	 * Set value of GuestUserRoleName
	 * @param context
	 * @param guestuserrolename
	 */
	public final void setGuestUserRoleName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String guestuserrolename)
	{
		getMendixObject().setValue(context, MemberNames.GuestUserRoleName.toString(), guestuserrolename);
	}

	/**
	 * @return value of ModelerFileName
	 */
	public final java.lang.String getModelerFileName()
	{
		return getModelerFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelerFileName
	 */
	public final java.lang.String getModelerFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelerFileName.toString());
	}

	/**
	 * Set value of ModelerFileName
	 * @param modelerfilename
	 */
	public final void setModelerFileName(java.lang.String modelerfilename)
	{
		setModelerFileName(getContext(), modelerfilename);
	}

	/**
	 * Set value of ModelerFileName
	 * @param context
	 * @param modelerfilename
	 */
	public final void setModelerFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelerfilename)
	{
		getMendixObject().setValue(context, MemberNames.ModelerFileName.toString(), modelerfilename);
	}

	/**
	 * @return value of ResourcesPath
	 */
	public final java.lang.String getResourcesPath()
	{
		return getResourcesPath(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourcesPath
	 */
	public final java.lang.String getResourcesPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourcesPath.toString());
	}

	/**
	 * Set value of ResourcesPath
	 * @param resourcespath
	 */
	public final void setResourcesPath(java.lang.String resourcespath)
	{
		setResourcesPath(getContext(), resourcespath);
	}

	/**
	 * Set value of ResourcesPath
	 * @param context
	 * @param resourcespath
	 */
	public final void setResourcesPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcespath)
	{
		getMendixObject().setValue(context, MemberNames.ResourcesPath.toString(), resourcespath);
	}

	/**
	 * @return value of TempPath
	 */
	public final java.lang.String getTempPath()
	{
		return getTempPath(getContext());
	}

	/**
	 * @param context
	 * @return value of TempPath
	 */
	public final java.lang.String getTempPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TempPath.toString());
	}

	/**
	 * Set value of TempPath
	 * @param temppath
	 */
	public final void setTempPath(java.lang.String temppath)
	{
		setTempPath(getContext(), temppath);
	}

	/**
	 * Set value of TempPath
	 * @param context
	 * @param temppath
	 */
	public final void setTempPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String temppath)
	{
		getMendixObject().setValue(context, MemberNames.TempPath.toString(), temppath);
	}

	/**
	 * @return value of SessionTimeout
	 */
	public final java.lang.Long getSessionTimeout()
	{
		return getSessionTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionTimeout
	 */
	public final java.lang.Long getSessionTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SessionTimeout.toString());
	}

	/**
	 * Set value of SessionTimeout
	 * @param sessiontimeout
	 */
	public final void setSessionTimeout(java.lang.Long sessiontimeout)
	{
		setSessionTimeout(getContext(), sessiontimeout);
	}

	/**
	 * Set value of SessionTimeout
	 * @param context
	 * @param sessiontimeout
	 */
	public final void setSessionTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sessiontimeout)
	{
		getMendixObject().setValue(context, MemberNames.SessionTimeout.toString(), sessiontimeout);
	}

	/**
	 * @return value of CoreConfiguration_Core
	 */
	public final runtime_core.proxies.Core getCoreConfiguration_Core() throws com.mendix.core.CoreException
	{
		return getCoreConfiguration_Core(getContext());
	}

	/**
	 * @param context
	 * @return value of CoreConfiguration_Core
	 */
	public final runtime_core.proxies.Core getCoreConfiguration_Core(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		runtime_core.proxies.Core result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CoreConfiguration_Core.toString());
		if (identifier != null)
			result = runtime_core.proxies.Core.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CoreConfiguration_Core
	 * @param coreconfiguration_core
	 */
	public final void setCoreConfiguration_Core(runtime_core.proxies.Core coreconfiguration_core)
	{
		setCoreConfiguration_Core(getContext(), coreconfiguration_core);
	}

	/**
	 * Set value of CoreConfiguration_Core
	 * @param context
	 * @param coreconfiguration_core
	 */
	public final void setCoreConfiguration_Core(com.mendix.systemwideinterfaces.core.IContext context, runtime_core.proxies.Core coreconfiguration_core)
	{
		if (coreconfiguration_core == null)
			getMendixObject().setValue(context, MemberNames.CoreConfiguration_Core.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CoreConfiguration_Core.toString(), coreconfiguration_core.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coreConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final runtime_core.proxies.CoreConfiguration that = (runtime_core.proxies.CoreConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Runtime_Core.CoreConfiguration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
